### ISSUE TITLE
MVP0 landing page

### ISSUE THREAD

**Issue by LibbyUX** [cns-iu/hra-portal-mvp0#4]
# Landing Page Breakpoints

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/9eae1017-33e0-4ebd-9a8a-b59344129b2c)

## XSmall (320x 568 iPhone SE)
- [Design File](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1776-18255&mode=design&t=osbr7wYhimhgi7n7-4)
- [Prototype Preview](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1776%3A18151&type=design&node-id=1776-18255&viewport=-2234%2C35%2C0.32&t=PSsfdKyc0r2ItTnO-1&scaling=scale-down&mode=design)

## Small (554x964)
- [Design File](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1753-16673&mode=design)
- [Prototype Preview](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1753%3A16673&type=design&node-id=1753-16805&viewport=-23%2C-50%2C0.23&t=ewHFxy7jQQH4Aafa-1&scaling=scale-down&mode=design)

## Medium (768x1024 iPad Mini)
- [Design File](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1894-5685&mode=design&t=osbr7wYhimhgi7n7-4)
- [Prototype Preview](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1894%3A5684&type=design&node-id=1894-5685&viewport=-567%2C88%2C0.38&t=cfJ65EtHHIs2nvT3-1&scaling=scale-down&mode=design)

## Large (1012x588)
- [Design File](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1895-6107&mode=design&t=osbr7wYhimhgi7n7-4)
- [Prototype Preview](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1895%3A6106&type=design&node-id=1895-6107&viewport=-485%2C221%2C0.29&t=W66qRsULtuQj3AHd-1&scaling=scale-down&mode=design)

## XL (1280x832 MacBook Air)
- [Design File](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1895-6792&mode=design&t=osbr7wYhimhgi7n7-4)
- [Prototype Preview](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1895%3A6791&type=design&node-id=1895-6792&viewport=-1663%2C-25%2C0.56&t=yEJwRc4IhTimHXnK-1&scaling=scale-down&mode=design)

## XXL (1440x900 MacBook Air 12-inch)
- [Design File](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1895-7587&mode=design&t=osbr7wYhimhgi7n7-4)
- [Prototype Preview](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1895%3A7586&type=design&node-id=1895-7587&viewport=-1174%2C-233%2C0.57&t=uEhX8UtDajGHd4zP-1&scaling=scale-down&mode=design)

## XXXL (1920x1080)
- [Design File](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=297-1745&mode=design&t=osbr7wYhimhgi7n7-4)
- [Prototype Preview](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=276%3A1145&type=design&node-id=297-1745&viewport=-668%2C-193%2C0.31&t=mqX3EXs8e1WmPJ3D-1&scaling=scale-down&starting-point-node-id=297%3A1745&show-proto-sidebar=1&mode=design)

# Resources

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/7676cda7-50e4-4801-8a25-ca6bc4951a5f)

## HRA Design System: Figma Design System File
- [Style Guide](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=0-1&mode=design)
- [Component Library](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=103-4&mode=design)

## User Stories for Development
- [Navigation User Stories](https://github.com/hubmapconsortium/hra-ui/wiki/HRA-Design-MVP0#hra-design-system-figma-design-system-file)
- [Landing Page User Stories](https://github.com/hubmapconsortium/hra-ui/wiki/HRA-Design-MVP0#hra-design-system-figma-design-system-file)

## Notes
- Modeled after [Primer's Breakpoints](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=276%3A1145&type=design&node-id=297-1745&viewport=-668%2C-193%2C0.31&t=mqX3EXs8e1WmPJ3D-1&scaling=scale-down&starting-point-node-id=297%3A1745&show-proto-sidebar=1&mode=design)

**Comment by LibbyUX** [comment]
# Design Review: Landing - Medium (768x1024 iPad Mini)

Thanks for getting this breakpoint over for review, @bhushankhope! It's looking great!

- [Development prototype](https://cns-iu.github.io/hra-portal-mvp0/)
- [Figma design file](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1894-5685&mode=design&t=xCyusNdYQ9lGB9Mo-4)

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/38b884dc-2630-43e6-8e9d-87fad7d76a05)


## Development Feedback
- The splash image appears a little pixelated
- The horizontal scrollbar needs to be removed from the collaborator section and a horizontal scroll feature will be added
- Hover states are needed everywhere in the footer menu

## Design Updates
- [Splash container](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1894-5686&mode=design&t=xCyusNdYQ9lGB9Mo-4) size and vertical padding have been adjusted
- Increased upper vertical padding on the [collaborator section heading container](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1894-5694&mode=design&t=xCyusNdYQ9lGB9Mo-4)
- Adjusted position of [collaborators frame](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1894-5697&mode=design&t=xCyusNdYQ9lGB9Mo-4), so it's more central within the overall frame
- [Footer Menu](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2033-10123&mode=design&t=U3IotTqcAxOEwrAc-4)
  - Spacing and padding adjustments in the top [part of the menu](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2033-9986&mode=design&t=U3IotTqcAxOEwrAc-4)
    - Many [individual spacing + padding adjustments](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2033-9987&mode=design&t=U3IotTqcAxOEwrAc-4) in the top area
  - Adjustments to the spacing of [menu frames](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2033-10010&mode=design&t=U3IotTqcAxOEwrAc-4)
  - Renamed layers so they are easier to understand

**Comment by LibbyUX** [comment]
New **Ready for dev** sections have been added to all breakpoint pages. 

Everything outside of these sections is not ready for development. Let me know if you have questions!

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/da8e169b-847d-49a2-98e4-76dcfde9b9d5)

**Comment by bhushankhope** [comment]
@libby-maier I have implemented the mobile menu for 320px breakpoint, please review and let me know your feedback. Thanks
https://cns-iu.github.io/hra-portal-mvp0/

**Comment by bhushankhope** [comment]
@libby-maier Just implemented the mobile menu for Small breakpoint(544*964). please review and let me know your feedback. Thanks
https://cns-iu.github.io/hra-portal-mvp0/

**Comment by bhushankhope** [comment]
@libby-maier I have implemented the XXL breakpoint (1,440px * 900px). Please review and let me know your feedback. Thanks.
https://cns-iu.github.io/hra-portal-mvp0/

**Comment by LibbyUX** [comment]
## Design Review: Mobile 320px
> @libby-maier I have implemented the mobile menu for 320px breakpoint, please review and let me know your feedback. Thanks https://cns-iu.github.io/hra-portal-mvp0/

### Mobile Menu Questions & Feedback
- Are the type fonts exactly as specified? I want to confirm this because the kerning (space between letters) appears larger in the build.
- The arrow icons appear to be a lighter shade in all navigation menus. They also appear larger than specified. Does this match the specification?
- Does all spacing/padding match the specification?
- The s in both CSV and SVG looks smaller than the other capital letters in the copy in production. Is the S capitalized and are we using the specified type font?
- The HRA logo looks blurry and low res. Is this the specified version?
- I don't see hover states for any of the buttons with specified hover states in the menu and the floating FAB on the landing page.
- **Edited during the meeting:** The Access Data looks like it has a selected state in production. Let's go with the ready/default state
- The animation of the chevron icon, when users expand more/less, looks great!

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/6e24ae0e-3b5f-487e-9d2e-486444a8c921)

### Landing Page Feedback
- Do all fonts match the spec exactly? There appear to be kerning and weight discrepancies, so I want to verify.
- Hover states are still needed on this landing page breakpoint for all buttons with specified hover states in the splash section, use the access section and the footer.
- Are you still working on the scrolling feature? I see it scrolls right when I get in line with the HuBMAP logo, but it would be nice if it triggered the horizontal scroll right when the user gets in that blue section. Let me know if we need to adjust our expectations for this ask.

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/7b63e1f9-1f2e-44d2-aa78-b7b6126f588f)

### 320px Resources
- [Figma design file](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1776-18255&mode=design&t=gqNHUpoWFQBLUVk6-4)
- [Figma prototype presentation](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1776%3A18151&type=design&node-id=1776-18255&t=gqNHUpoWFQBLUVk6-0&scaling=scale-down&starting-point-node-id=1776%3A18255)

Thank you for working on this, @bhushankhope! It's looking great!

**Comment by LibbyUX** [comment]
## Design Review: Mobile 544px

Thanks so much, @bhushankhope! This breakpoint is looking great too! 

> @libby-maier Just implemented the mobile menu for Small breakpoint(544*964). please review and let me know your feedback. Thanks
https://cns-iu.github.io/hra-portal-mvp0/

### Mobile Menu Questions & Feedback
- Looking at the menu expand more and less button font: Is this the same size as the page buttons just below it? It looks slightly bigger in production when these were specified with the same font style in Figma.
  - The file format type font captions seem a little larger than the specification.
  - Verify all fonts in the build match the spec font styles.
- Verify spacing & padding match the spec.
- Verify all colors match the spec (specifically for the arrow icon).
- Hover states are needed wherever they have been specified.
- The logo appears a little clipped on the right side.

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/fb532af0-fedd-42f9-bdda-ea224323bb5c)


### Landing Page Feedback
- Do all fonts match the spec exactly? The primary CTA button looks bold.
- Regarding the primary CTA button, is the text centered on the button precisely? It looks slightly shorter in height than specified. Depending on the answer, I might need to change it to make it taller.
- Hover states are still needed on this landing page breakpoint for all buttons with specified hover states in the splash section, use the access section and the footer.
- Are you still working on the scrolling feature? I see it scrolls right when I get in line with the HuBMAP logo, but it would be nice if it triggered the horizontal scroll right when the user gets in that blue section. Let me know if we need to adjust our expectations for this ask.

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/919f6d1b-e81a-4894-8d07-668ea9a098bf)

### 544px Resources
- [Figma design file](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1753-16805&mode=design&t=gqNHUpoWFQBLUVk6-4)
- [Figma prototype presentation](https://www.figma.com/proto/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?page-id=1753%3A16673&type=design&node-id=1753-16805&t=gqNHUpoWFQBLUVk6-0&scaling=scale-down&starting-point-node-id=2033%3A10567)

**Comment by LibbyUX** [comment]
## Design Review: Landing 1440px

> @libby-maier I have implemented the XXL breakpoint (1,440px * 900px). Please review and let me know your feedback. Thanks. https://cns-iu.github.io/hra-portal-mvp0/

Thanks so much, @bhushankhope! This is looking super.

### Feedback & Questions
- The logo looks lower resolution. Is there a way to fix this?
- The CTA button seems to be using a heavier weight than specified. Is this accurate?
- States are needed for all buttons that have specified states.

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/834e448e-4b1e-4354-850a-b3157bac6bb7)

**Comment by LibbyUX** [comment]
Hi @bhushankhope -

The [768px navigation hamburger menu component](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2297-10336&mode=design&t=gqNHUpoWFQBLUVk6-4) is ready for dev!

**Comment by LibbyUX** [comment]
# Meeting with Bhushan 12:15-1p:
- The top padding for the menu is fine in breakpoints.
- No states for mobile within Inspect on Google Chrome, but states will show on the browser when Inspect is closed.
  - Review browser sizes without using Inspect for larger breakpoints for browser views.
  - Also, use this setting:
![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/0ff18d86-aae1-4c33-a7f1-6074c50ab955)
- Libby to re-review states in the browser settings.
- Libby will discuss the font appearance online with Ushma (when she is back from vacation on 3/26).

**Comment by LibbyUX** [comment]
Hi @bhushankhope, thanks for the great meeting today! The states look good on browser!

 I just finalized the design for the [1012px nav menu component](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2628-27835&mode=design&t=gqNHUpoWFQBLUVk6-4) and moved it to the ready-for-dev section.
 
Thanks so much!

**Comment by bhushankhope** [comment]
@libby-maier Implemented mobile menu for Medium breakpoint (768px)

**Comment by LibbyUX** [comment]
> @libby-maier Implemented mobile menu for Medium breakpoint (768px)

Thank you, @bhushankhope! That was quick! 

![D15D0366-0DA9-4884-9F4C-8CCAFFCE4C70](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/af7e84f0-8f7c-4142-910c-e8d70ec4f029)

# Design Review: Landing 768px
- Reviewed in browser without the inspect tool
### Menu
- The hamburger menu icon and the close menu icon should be in the same spot. Currently the jump around a little bit. Can we get this closer to the spec?
- The fade effect goes over the top of the browser window bar.
- The Open in New icon should change colors with the button's different states. See the [Figma Design System file](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=1941-408&mode=design&t=x3q4xw7j4KQf3p3S-4) for this component.

### Landing
- I think you mentioned today that you're still working on the button states for the footer. I'll keep an eye out for those eventually!

This is looking great otherwise! Thanks so much!

**Comment by LibbyUX** [comment]
@bhushankhope - I have completed the navigation menus for [1280px](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2661-37861&mode=design&t=5bUEQqWnnc1S70iW-4) & [1440px](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2661-39505&mode=design&t=5bUEQqWnnc1S70iW-4). All nav menus have been moved to their ready for dev sections on their specific breakpoint page!

**Comment by bhushankhope** [comment]
implemented mobile menu for 1012px breakpoint. @libby-maier

**Comment by LibbyUX** [comment]
> implemented mobile menu for 1012px breakpoint. @libby-maier

Thank you, @bhushankhope !

My feedback on the 1012px breakpoint is the same feedback from [my review of the 768px breakpoint](https://github.com/cns-iu/hra-portal-mvp0/issues/4#issuecomment-2007987147). Please let me know if you have questions!

**Comment by bhushankhope** [comment]
@libby-maier I have created the navigation menu for xl, xxl and xxxl screens, Added hover states to remaining menus. Please let me know if anything needs to be changed. Thanks

**Comment by LibbyUX** [comment]
> @libby-maier I have created the navigation menu for xl, xxl and xxxl screens, Added hover states to remaining menus. Please let me know if anything needs to be changed. Thanks

Thanks @bhushankhope! It's looking good!

## 1920x menu feedback
- Please check the active/pressed state of the main nav buttons. The underlined bar and text need to be the same color when pressed.
- Verify the spacing of the nav menu item button font and "open in new" icon match the spec. It looks more spacious in the specification.
- Explore flyout menu: The alignment of the compass icon needs to match the spec.

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/f5f5bbd3-10dd-4e4d-a61e-b22e221dc449)

## 1440px menu feedback
- Same feedback about the active/pressed states of the main navigation category buttons.
- Same feedback on the spacing of the external routing button fonts and "open in new" icon.
- Contribute flyout menu: The ASCT+B Reporter menu button is bugging out and throwing off the symmetry of this component.

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/68335f0a-90b0-4d6e-a4d8-39df5aa36c26)

## 1280px menu feedback
- Same feedback about the Explore flyout menu
- Same feedback about the Contribute flyout menu

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/cebb1e80-2eb6-48fa-a3a5-8e93a85d4a45)
![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/89993a40-a67c-4a39-a151-249c819f184b)

## Resizing between 1280px to 1012px
- Can we implement the hamburger menu once browser sizes are reduced below 1280px? This is currently too cluttered and certain buttons are obscured. We don't want to see a horizontal scroll bar.

![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/67f3e0ab-d593-4a78-95f5-b62151c60845)
![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/73d579ec-e7a6-4154-94bd-1bfa95558cbe)
![image](https://github.com/cns-iu/hra-portal-mvp0/assets/97060856/b1bd0f55-059e-4de8-a996-0605b4d09a8c)

**Comment by bhushankhope** [comment]
@libby-maier fixed all the above issues.

**Comment by bhushankhope** [comment]
@libby-maier I have implemented the scroll functionality. Please review. Thanks.

**Comment by LibbyUX** [comment]
Hey @bhushankhope, I glanced just now, and it looks good. 

We may tweak the responsive resizing of the footer for some breakpoints.

I will ping when I arrive at the office tomorrow so we can meet. Thanks!

**Comment by LibbyUX** [comment]
@bhushankhope and I met this morning and made a few minor changes. 

He is checking a few components after we made some small adjustments:
- We updated the mage in the splash section to show the human better between 1012 and 1280
- We updated the spacing on the footer navigation to 2 rem
- Bhushan adding infoccf@indiana.edu as the mailto: email in the footer

**Comment by LibbyUX** [comment]
We met again! We discussed the responsive resizing of the footer between widths 1440px and 1920px. 

Getting closer!

**Comment by bhushankhope** [comment]
@LibbyUX I have made the changes as we discussed.

**Comment by LibbyUX** [comment]
Fabulous, thank you @bhushankhope! Ushma and I will review MVP0 later this afternoon!

**Comment by u-p-design** [comment]
@bhushankhope We have updated Omnes font with Nunito Sans

**Comment by bhushankhope** [comment]
Updated font to Nunito Sans

**Comment by LibbyUX** [comment]
@bhushankhope - I have implemented the following changes in Figma:

- Updated all instances of Organ Gallery in VR and VR Organ Gallery to **HRA Organ Gallery**
  - All breakpoint navigation menus and footers
- Updated Contribute secondary navigation button to Get Involved
  - [1920px breakpoint](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=943-18861&mode=design&t=6F3S1KItQCTqkdIG-4)
  - [320px breakpoint](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2102-16222&mode=design&t=6F3S1KItQCTqkdIG-4)
- Reduced footer padding in both sections on [544px breakpoint](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2033-10567&mode=design&t=6F3S1KItQCTqkdIG-4)
- Swapped Consortia section Heading 4 for Heading 3 on two breakpoints:
  - [544px breakpoint](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2033-8891&mode=design&t=6F3S1KItQCTqkdIG-4)
  - [320px breakpoint](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1776-18263&mode=design&t=6F3S1KItQCTqkdIG-4)
- Updated the Contribute menu so that the buttons are aligned on both sides
  - [1920px](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=943-18861&mode=design&t=6F3S1KItQCTqkdIG-4)
  - [1440px](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2661-39567&mode=design&t=6F3S1KItQCTqkdIG-4)
  - [1280px](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2661-39208&mode=design&t=6F3S1KItQCTqkdIG-4)
 

Let me know when this is completed and I will send out the MVP0 for review!

**Comment by bhushankhope** [comment]
@LibbyUX made above changes in PR #32

**Comment by LibbyUX** [comment]
# Design to Dev Updates for HRA Redesign MVP0 (if time allows) or MVP1
Hi @bhushankhope, here are the current updates based on the [MVP0 review](https://docs.google.com/document/d/1ekIPM-B7-AL2ipBtHStXrjzeQzyTN4t5zOnrwi2vgpg/edit#heading=h.1ok8b5i2p8d3). Also, I am mentioning @u-p-design for visibility!

# Global updates & design system updates

### All HRA category icons resized
- Sizes reduced in both sets of [category icons](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=1775-24&mode=design&t=gj1vvzYy9fvtMGuo-4) and [their rounded button component](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=1799-539&mode=design&t=gj1vvzYy9fvtMGuo-4) for all landing pages

### Significant updates to footer components
The [footer component](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=3385-17883&mode=design&t=s0C3xi4HDV3SFUe2-4) was one of the biggest sources of issues during the review. Please ensure each breakpoint is well inspected and as close to spec as possible.
- Spacing and padding adjusted on nearly every component breakpoint
- 430px breakpoint variant added
- Logos updated
- [Secondary navigation](https://www.figma.com/file/gQEMLugLjweDvbsNNUVffD/Human-Reference-Atlas-Design-System?type=design&node-id=1948-1094&mode=design&t=s0C3xi4HDV3SFUe2-4) buttons updated: smaller variant added and font styles updated
- Font styles updated on every breakpoint for CNS Copyright, Funded By, and Medical Disclaimer text

# Breakpoint updates

### 320px breakpoint
[Splash](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1776-18256&mode=design&t=CqERvo6DDLW4k9F1-4) section:
- Vertical padding and vertical height adjusted
- Spacing adjusted in text container

[Consortia](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1776-25617&mode=design&t=KZ5IhPXnnVNO8JGC-4) section:
- Vertical height and vertical padding updates to make this section smaller

[Use the Atlas](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1776-18275&mode=design&t=KZ5IhPXnnVNO8JGC-4) section:
- Icon size reduced in Use the Atlas Section
- Vertical padding reduced
- Spacing reduced in container
- Spacing in category containers reduced

### Breakpoint Added: 430x932
- A new breakpoint has been specified because the reviewers require excellent mobile experiences.
- Please see [430x932 XSmall iPhone 15 & 16](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=3092-22395&mode=design&t=CqERvo6DDLW4k9F1-4)
- XSmall iPhone SE has been renamed to XXSmall

### 544px breakpoint
[Splash](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1753-16806&mode=design&t=SCfanyiQ3pio1PnK-4) section:
- Font updated
- Vertical padding and vertical height adjusted

[Consortium](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=2033-8891&mode=design&t=SCfanyiQ3pio1PnK-4) section:
- Font updated
- Vertical padding and vertical height adjusted

[Use the Atlas](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1753-16826&mode=design&t=SCfanyiQ3pio1PnK-4) section:
- Font updates
- Icon size reduced
- Spacing updates
- Smaller button variant used

### 768px breakpoint
[Use the Atlas](https://www.figma.com/file/AwS7caXwnBn1AqgiG93Zxn/HRA-Portal-Redesign---7th-Release-(v2.1)?type=design&node-id=1894-5706&mode=design&t=SCfanyiQ3pio1PnK-4) section:
- Horizontal padding decreased to match footer

**Comment by LibbyUX** [comment]
Issue superseded by https://github.com/hubmapconsortium/hra-ui/issues/356

Thanks for everything @bhushankhope! Closing this one out now!
